export const SET_YEAR = 'SET_YEAR'
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'
export const SET_SEARCH_ITEMS = 'SET_SEARCH_ITEMS'
export const SET_DETAILED_ITEM = 'SET_DETAILED_ITEM'
export const CLEAN_DETAILED_ITEM = 'CLEAN_DETAILED_ITEM'

